In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"E:\archive (5).zip")

In [3]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [4]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [5]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    df.drop(columns=['has_covid']),
    df['has_covid'],
    test_size=0.2,
    random_state=42
)

In [8]:
x_test

    age  gender  fever   cough       city
83   17  Female  104.0    Mild    Kolkata
53   83    Male   98.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi
39   50  Female  103.0    Mild    Kolkata
22   71  Female   98.0  Strong    Kolkata
80   14  Female   99.0    Mild     Mumbai
10   75  Female    NaN    Mild      Delhi
0    60    Male  103.0    Mild    Kolkata
18   64  Female   98.0    Mild  Bangalore
30   15    Male  101.0    Mild      Delhi
73   34    Male   98.0  Strong    Kolkata
33   26  Female   98.0    Mild    Kolkata
90   59  Female   99.0  Strong      Delhi
4    65  Female  101.0    Mild     Mumbai
76   80    Male  100.0    Mild  Bangalore
77    8  Female  101.0    Mild    Kolkata
12   25  Female   99.0  Strong    Kolkata
31   83    Male  103.0    Mild    Kolkata

In [9]:
y_test

83     No
53    Yes
70     No
45     No
44     No
39     No
22    Yes
80    Yes
10     No
0      No
18    Yes
30    Yes
73    Yes
33     No
90     No
4      No
76    Yes
77     No
12     No
31     No
Name: has_covid, dtype: object

In [10]:
y_train

55    Yes
88     No
26    Yes
42    Yes
69     No
     ...
60    Yes
71     No
14     No
92     No
51    Yes
Name: has_covid, Length: 80, dtype: object

In [11]:
x_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

# without column transformation

In [15]:
from sklearn.impute import SimpleImputer

# Create the imputer object
si = SimpleImputer()

# Fit on the training data and transform it
x_train_fever = si.fit_transform(x_train[['fever']])

# Use the same fitted imputer to transform the test data
x_test_fever = si.transform(x_test[['fever']])

# Check the shape
x_train_fever

array([[101.],
       [100.],
       [100.],
       [100.],
       [103.],
       [103.],
       [102.],
       [101.],
       [101.],
       [101.],
       [ 98.],
       [104.],
       [103.],
       [104.],
       [100.],
       [101.],
       [104.],
       [102.],
       [102.],
       [103.],
       [104.],
       [102.],
       [101.],
       [104.],
       [102.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [102.],
       [100.],
       [ 98.],
       [ 98.],
       [101.],
       [100.],
       [100.],
       [101.],
       [104.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 99.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [ 98.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 98.],
       [ 99.],
       [102.],
       [101.],
       [101.],
       [104.],
       [100.],
       [ 98.],
       [100.],
       [101.],
       [100.],
       [100.],
       [ 98.],
       [101.],
       [ 98.],
       [101.],
       [101.],
       [104.],
       [104.],
       [ 98.],
       [ 98.],
       [102.],
       [104.],
       [104.],
       [102.],
       [100.]])

In [18]:
from sklearn.preprocessing import OrdinalEncoder

# Create the encoder
oe = OrdinalEncoder(categories=[['Mild', 'Strong']])

# Fit and transform the training data
x_train_cough = oe.fit_transform(x_train[['cough']])

# Transform the test data using the same encoder
x_test_cough = oe.transform(x_test[['cough']])

# View the encoded training data
x_train_cough.shape

(80, 1)

In [22]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False)

# Fit on training data
x_train_gender_city = ohe.fit_transform(x_train[['gender', 'city']])

# Transform test data
x_test_gender_city = ohe.transform(x_test[['gender', 'city']])

print(x_train_gender_city.shape)

(80, 4)

In [25]:
# Extracting age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
x_test_age = x_test.drop(columns=['gender','fever','cough','city']).values

x_train_age.shape

(80, 1)

In [26]:
x_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [28]:
x_train_transform = np.concatenate((x_train_age,x_train_fever,x_train_gender_city, x_train_cough), axis=1)
# also the test data 
x_train_transformed = np.concatenate((x_test_age,x_test_fever,x_test_gender_city, x_test_cough), axis=1)
x_train_transformed.shape

(20, 7)

# with column column transformation

In [29]:
from sklearn.compose import  ColumnTransformer

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

transformer = ColumnTransformer(
    transformers=[
        ('tnf1', SimpleImputer(), ['fever']),
        ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
        ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])
    ],
    remainder='passthrough'
)

In [46]:
import pandas as pd

x_train_transform = pd.DataFrame(
    transformer.fit_transform(x_train)
)

x_train_transform.head()

       0    1    2    3    4    5     6
0  101.0  0.0  0.0  0.0  0.0  1.0  81.0
1  100.0  0.0  0.0  0.0  1.0  0.0   5.0
2  100.0  0.0  0.0  0.0  1.0  0.0  19.0
3  100.0  0.0  1.0  1.0  0.0  0.0  27.0
4  103.0  0.0  0.0  1.0  0.0  0.0  73.0

In [47]:
import pandas as pd

x_train_transform = pd.DataFrame(
    transformer.fit_transform(x_train),
    columns=transformer.get_feature_names_out()
)

x_train_transform.head()

,tnf1__fever,tnf2__cough,tnf3__gender_Male,tnf3__city_Delhi,tnf3__city_Kolkata,tnf3__city_Mumbai,remainder__age
0,101.0,0.0,0.0,0.0,0.0,1.0,81.0
1,100.0,0.0,0.0,0.0,1.0,0.0,5.0
2,100.0,0.0,0.0,0.0,1.0,0.0,19.0
3,100.0,0.0,1.0,1.0,0.0,0.0,27.0
4,103.0,0.0,0.0,1.0,0.0,0.0,73.0

In [48]:
x_test_transform = pd.DataFrame(
    transformer.transform(x_test),
    columns=transformer.get_feature_names_out()
)

x_test_transform.head()

,tnf1__fever,tnf2__cough,tnf3__gender_Male,tnf3__city_Delhi,tnf3__city_Kolkata,tnf3__city_Mumbai,remainder__age
0,104.0,0.0,0.0,0.0,1.0,0.0,17.0
1,98.0,0.0,1.0,1.0,0.0,0.0,83.0
2,101.0,1.0,0.0,1.0,0.0,0.0,68.0
3,99.0,0.0,1.0,0.0,0.0,0.0,72.0
4,102.0,1.0,1.0,1.0,0.0,0.0,20.0

In [49]:
x_train_transform = transformer.fit_transform(x_train)

In [51]:
x_test_transform = transformer.transform(x_test)

In [52]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

transformer = ColumnTransformer(
    transformers=[
        ('tnf1', SimpleImputer(), ['fever']),
        ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
        ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])
    ],
    remainder='passthrough'
)

In [53]:
x_train_transform = transformer.fit_transform(x_train)

In [54]:
print(x_train_transform.shape)
print(x_test_transform.shape)

(80, 7)
(20, 7)

In [55]:
x_test_transform = transformer.transform(x_test)

In [56]:
print(x_train_transform[:5])

[[101.   0.   0.   0.   0.   1.  81.]
 [100.   0.   0.   0.   1.   0.   5.]
 [100.   0.   0.   0.   1.   0.  19.]
 [100.   0.   1.   1.   0.   0.  27.]
 [103.   0.   0.   1.   0.   0.  73.]]

In [57]:
print(x_test_transform[:5])

[[104.   0.   0.   0.   1.   0.  17.]
 [ 98.   0.   1.   1.   0.   0.  83.]
 [101.   1.   0.   1.   0.   0.  68.]
 [ 99.   0.   1.   0.   0.   0.  72.]
 [102.   1.   1.   1.   0.   0.  20.]]

In [58]:
print(transformer.get_feature_names_out())

['tnf1__fever' 'tnf2__cough' 'tnf3__gender_Male' 'tnf3__city_Delhi'
 'tnf3__city_Kolkata' 'tnf3__city_Mumbai' 'remainder__age']