In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

from sklearn.compose import ColumnTransformer

In [3]:
df = pd.read_csv(r"E:\archive\tested.csv")

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [7]:
df.dropna(inplace=True)

In [8]:
df.shape

(87, 12)

In [9]:
df = pd.read_csv(r"E:\archive\tested.csv", usecols=['Age','Fare','Survived'])

In [10]:
df

     Survived   Age      Fare
0           0  34.5    7.8292
1           1  47.0    7.0000
2           0  62.0    9.6875
3           0  27.0    8.6625
4           1  22.0   12.2875
..        ...   ...       ...
413         0   NaN    8.0500
414         1  39.0  108.9000
415         0  38.5    7.2500
416         0   NaN    8.0500
417         0   NaN   22.3583

[418 rows x 3 columns]

In [11]:
df.dropna(inplace=True)

In [12]:
df.head()

   Survived   Age     Fare
0         0  34.5   7.8292
1         1  47.0   7.0000
2         0  62.0   9.6875
3         0  27.0   8.6625
4         1  22.0  12.2875

In [13]:
df.shape

(331, 3)

In [14]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [15]:
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [16]:
x_train.head(2)

       Age    Fare
281   0.75  13.775
96   76.00  78.850

In [17]:
x_test.head(2)

      Age    Fare
27   22.5   7.225
389   6.0  21.075

In [18]:
y_train.head(2)

281    0
96     1
Name: Survived, dtype: int64

In [19]:
y_test.head(2)

27     0
389    0
Name: Survived, dtype: int64

In [20]:
clf = DecisionTreeClassifier()

In [21]:
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [22]:
accuracy_score(y_test, y_pred)

0.5671641791044776

In [23]:
np.mean(cross_val_score(DecisionTreeClassifier(),x,y, cv=10, scoring='accuracy'))

np.float64(0.5619429590017825)

In [24]:
from sklearn.preprocessing import KBinsDiscretizer
kbin_age = KBinsDiscretizer(n_bins=10, encode='original',strategy='quantile')
kbin_fare = KBinsDiscretizer(n_bins=10, encode='original',strategy='quantile')

In [25]:
trf = ColumnTransformer([
    ('first',kbin_age,[0]),
    ('second',kbin_fare,[1])])

In [26]:
from sklearn.preprocessing import KBinsDiscretizer

kbin_age = KBinsDiscretizer(
    n_bins=10,
    encode='ordinal',
    strategy='quantile'
)

kbin_fare = KBinsDiscretizer(
    n_bins=10,
    encode='ordinal',
    strategy='quantile'
)

In [27]:
from sklearn.model_selection import train_test_split

# Features
X = df.drop('Survived', axis=1)

# Target
y = df['Survived']

# Train-test split
x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)

x_train shape: (264, 2)
x_test shape: (67, 2)

In [29]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

InvalidParameterError: The 'encode' parameter of KBinsDiscretizer must be a str among {'ordinal', 'onehot', 'onehot-dense'}. Got 'original' instead.

In [28]:
trf.named_transformers_['first'].bin_edges

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'

In [31]:
trf.named_transformers_['first'].bin_edges_

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'

In [32]:
ootput = pd.DataFrame({
    'age':x_train['Age'],
    'age_trf':x_train_trf[:,0],
    'fare':x_train['fare'],
    'fare_trf':x_train_trf[:,1]
})

NameError: name 'x_train_trf' is not defined

In [33]:
output['age_labels'] = pd.cut(x=x_train['Age'],
                              bins=trf.named_transformers_['first'].bins_edges_[0].tolist())
out['fare_labels'] = pd.cut(x=x_train['Fare'],
                            bins=trf.named_transformers_['second'].bins_edges_[0].tolist())

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'

In [34]:
output.sample(5)

NameError: name 'output' is not defined

In [35]:
clf = DecisionTreeClassifier()
clf.fit(x_train_trf,y_train)
y_pred2 = clf.predict(x_test_trf)

NameError: name 'x_train_trf' is not defined

In [36]:
accuracy_score(y_test,y_pred2)

NameError: name 'y_pred2' is not defined

In [37]:
x_trf = trf.fit_transform(x)
np.mean(cross_val_score(DecisionTreeClassifier(), x,y, cv=10,scoring='acuuracy'))

InvalidParameterError: The 'encode' parameter of KBinsDiscretizer must be a str among {'ordinal', 'onehot', 'onehot-dense'}. Got 'original' instead.